export const STAR_PLAYERS = [
  'Nikola Jokic',
  'Giannis Antetokounmpo',
  'Luka Doncic',
  'Shai Gilgeous-Alexander',
  'Anthony Edwards',
  'Jayson Tatum',
  'Stephen Curry',
  'LeBron James',
  'Kevin Durant',
  'Victor Wembanyama',
  'Joel Embiid',
  'Ja Morant',
  'Tyrese Haliburton',
  'Devin Booker',
  'Donovan Mitchell',
  'Chet Holmgren',
  'Jalen Brunson',
  'Anthony Davis',
  'Kyrie Irving',
  'Jalen Williams',
]
